const CONSTANTES = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLERCER_SESION: 'ESTABLERCER_SESION',
  CERRAR_SESION: 'CERRAR_SESION',
  LIMPIAR_IMAGEN_SIGNUP: 'LIMPIAR_IMAGEN_SIGNUP',
  CARGAR_IMAGEN_SIGNUP: 'CARGAR_IMAGEN_SIGNUP',
  CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dh0qf6n8n/image/upload',
  CLOUDINARY_PRESET: 'p0nxbs1w',
  CARGAR_IMAGEN_PUBLICACION: 'CARGAR_IMAGEN_PUBLICACION',
  LIMPIAR_IMAGEN_PUBLICACION: 'LIMPIAR_IMAGEN_PUBLICACION',
  SUBIR_PUBLICACION: 'SUBIR_PUBLICACION',
  DESCARGAR_PUBLICACIONES: 'DESCARGAR_PUBLICACIONES',

  API_NODE_UPLOAD: 'http://localhost:3030/profile',
};

export default CONSTANTES;
